---
- name: install dependancies
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - php5-sqlite
    - php5-gd
    - unzip


- name: copy latest Kanboard source
  unarchive:
    src: https://kanboard.net/kanboard-latest.zip
    dest: /data/www/docroot
    remote_src: yes
