---
- name: install dependancies
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - php5-sqlite
    - php5-gd
    - unzip

- name: download latest Kanboard
  become: yes
  become_user: www-data
  get_url:
    url: https://kanboard.net/kanboard-latest.zip
    dest: /tmp/kanboard.zip
    mode: 0666

- name: copy latest Kanboard source
  become: yes
  become_user: www-data
  unarchive:
    src: /tmp/kanboard.zip
    dest: /data/www/docroot
    remote_src: no
